FROM debian:jessie

ENV OTP_VERSION=17.5 REBAR_VERSION=2.5.1

RUN DEBIAN_FRONTEND=noninteractive  \
    apt-get update -qq \
    && apt-get install -y \
       build-essential \
       git \
       libncurses5-dev \
       openssl \
       libssl-dev \
       fop \
       xsltproc \
       unixodbc-dev \
       curl

ADD http://erlang.org/download/otp_src_${OTP_VERSION}.tar.gz /usr/src/
RUN cd /usr/src \
    && tar xf otp_src_${OTP_VERSION}.tar.gz \
    && cd otp_src_${OTP_VERSION} \
    && ./configure \
    && make \
    && make install \
    && cd / && rm -rf /usr/src/otp_src_${OTP_VERSION}

ADD https://github.com/rebar/rebar/archive/${REBAR_VERSION}.tar.gz  /usr/src/rebar-${REBAR_VERSION}.tar.gz
RUN cd /usr/src \
    && tar zxf rebar-${REBAR_VERSION}.tar.gz \
    && cd rebar-${REBAR_VERSION} \
    && make \
    && cp rebar /usr/bin/rebar \
    && cd / && rm -rf /usr/src/rebar-${REBAR_VERSION}

RUN mkdir -p /opt \
 && git clone --branch master --depth 1 https://github.com/rebar/rebar3.git /opt/rebar3 \
 && cd /opt/rebar3 \
 && ./bootstrap \
 && ln -s /opt/rebar3/rebar3 /usr/bin/rebar3

ADD ./start.bash ./snitch.bash /

CMD /start.bash
ONBUILD ADD ./run.bash /
